# Generated by Django 5.0.4 on 2024-05-06 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_questions_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 14, 47, 21, 546200, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 14, 47, 21, 546200, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
