# Generated by Django 5.0.4 on 2024-04-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=2000, null=True, unique=True, verbose_name='Ответ')),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 18, 10, 13, 27, 156780, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
    ]
