# Generated by Django 5.0.4 on 2024-04-18 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True, default='На этот вопрос пока нет ответа.', max_length=2000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 10, 32, 17, 851229, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
    ]
