# Generated by Django 5.0.4 on 2024-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_new_text_alter_new_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='new',
            name='some_info',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
