# Generated by Django 5.0.4 on 2024-04-17 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 17, 6, 12, 928430, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
