# Generated by Django 5.0.4 on 2024-04-18 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 9, 32, 10, 671696, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
