# Generated by Django 5.0.4 on 2024-04-18 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 11, 20, 24, 236902, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
