# Generated by Django 5.0.4 on 2024-09-05 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_questions_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 7, 58, 53, 375501, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 7, 58, 53, 376500, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
