# Generated by Django 5.0.4 on 2024-09-07 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_questions_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 9, 20, 41, 807937, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 9, 20, 41, 808937, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
