# Generated by Django 5.0.4 on 2024-09-05 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_partner_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 7, 58, 53, 372501, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
