# Generated by Django 5.0.4 on 2024-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0004_alter_medicines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines_images', verbose_name='Изображение'),
        ),
    ]
