# Generated by Django 5.0.4 on 2024-04-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0006_remove_categories_slug_remove_departments_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Компания-поставщик')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Закупочная цена')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicines.medicines', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
