# Generated by Django 5.0.4 on 2024-04-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
