# Generated by Django 5.0.4 on 2024-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Заработная плата')),
                ('some_info', models.TextField(max_length=1000, verbose_name='Описание должности')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
