# Generated by Django 5.0.4 on 2024-04-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
