# Generated by Django 5.0.4 on 2024-09-05 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_promotion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 8, 2, 9, 432192, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
