# Generated by Django 5.0.4 on 2024-09-07 09:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_companyinfo_props_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(null=True, upload_to='main_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 9, 27, 34, 70628, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
