# Generated by Django 5.0.4 on 2024-09-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='category',
            new_name='user',
        ),
    ]
