# Generated by Django 5.0.4 on 2024-04-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0002_alter_categories_slug_alter_departments_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Медикамент', 'verbose_name_plural': 'Медикаменты'},
        ),
        migrations.AddField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicines.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='instruction',
            field=models.TextField(verbose_name='Инструкция'),
        ),
    ]
