# Generated by Django 5.0.4 on 2024-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0003_alter_categories_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines_images/', verbose_name='Изображение'),
        ),
    ]
