# Generated by Django 5.0.4 on 2024-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0005_alter_medicines_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='slug',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines_images/', verbose_name='Изображение'),
        ),
    ]
