# Generated by Django 5.0.4 on 2024-05-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0008_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Providers',
        ),
    ]
