# Generated by Django 5.0.4 on 2024-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_new_image_alter_new_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
