# Generated by Django 5.0.4 on 2024-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_new_options_alter_new_some_info_alter_new_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='some_info',
            field=models.TextField(max_length=1000, verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
