# Generated by Django 5.0.4 on 2024-04-18 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 10, 32, 17, 835593, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
