# Generated by Django 5.0.4 on 2024-05-06 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 14, 47, 21, 530578, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
