# Generated by Django 5.0.4 on 2024-05-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 15, 40, 37, 752706, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
