# Generated by Django 5.0.4 on 2024-09-07 08:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_promotion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=2000, verbose_name='О компании')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='main_images/', verbose_name='Логотип')),
                ('history', models.CharField(max_length=2000, verbose_name='История по годам')),
                ('props', models.CharField(max_length=2000, verbose_name='Реквизиты')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='main_images/', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компаниях',
            },
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 8, 47, 42, 107909, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
