# Generated by Django 5.0.4 on 2024-09-07 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_companyinfo_alter_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(max_length=2000, verbose_name='История по годам'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='info',
            field=models.TextField(max_length=2000, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 9, 20, 41, 790939, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
