# Generated by Django 5.0.4 on 2024-09-07 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_companyinfo_history_alter_companyinfo_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='props',
            field=models.TextField(max_length=2000, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 9, 21, 22, 610736, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
